version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
      - echo "Starting Terraform Init..."
      - cd global
      - terraform init
      - terraform apply -auto-approve

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-app .
      - docker tag my-app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
      - echo "Pushing the Docker image to ECR..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest
      - echo "Writing image definitions file..."
      - printf '[{"name":"my-app","imageUri":"%s"}]' ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:latest > imagedefinitions.json

  post_build:
    commands:
      - echo "Deploying via Terraform..."
      - terraform apply -auto-approve
artifacts:
  files:
    - imagedefinitions.json
