version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform for global resources..."
      - cd global
      - terraform init

  build:
    commands:
      - echo "Applying Terraform for global resources..."
      - terraform apply -auto-approve

artifacts:
  files:
    - "**/*"
