version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies..."
      - docker --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Starting Docker build..."
      - docker build -t php-app .
      - docker tag php-app:latest ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/php-app:latest

  build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/php-app:latest
  
  post_build:
    commands:
      - echo "Updating ECS service with new image..."
      - printf '[{"name":"php-app","imageUri":"%s"}]' ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/php-app:latest > imagedefinitions.json
      # - aws ecs update-service --cluster dev-ecs-cluster --service php-service --force-new-deployment

artifacts:
  files:
  - imagedefinitions.json