version: 0.2

env:
  variables:
    APP_PATH: "environments/dev/php-app"

phases:
  install:
    # runtime-versions:
    #   docker: 19
    commands:
      - echo "Installing dependencies..."
      - docker --version

  pre_build:
    commands:
      - echo "REGION = ${AWS_REGION}"
      - echo "${AWS_REGION}"
      - export ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':') 
      - echo "Account ID is ${ACCOUNT_ID}"
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - echo "Starting Docker build..."
      - cd $APP_PATH
      - docker build -t php-app .
      - docker tag php-app:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/php-app:latest

  build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/php-app:latest
  
  post_build:
    commands:
      - echo "Updating ECS service with new image..."
      - cd $CODEBUILD_SRC_DIR
      - printf '[{"name":"php-app","imageUri":"%s"}]' ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/php-app:latest > imagedefinitions.json
      

artifacts:
  files:
  - "imagedefinitions.json"